# Siegfried Loeffler Marketing Demo with Ekinops OneAccess FlexCPE 
# June 2024

# configuration of the prometheus scraper
global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'promswarm'

scrape_configs:
  - job_name: 'localhost-prometheus-metrics'
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: ['localhost:9090']

# Gather SNMP data from the ONE621 on my desk
  - job_name: 'SNMP ONE621'
    static_configs:
    - targets: ['192.168.60.96']
      labels:
        job: 'One621'
    metrics_path: /snmp
    params:
      module: [if_mib, tcp_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.4.1:9116  # The SNMP exporter's real hostname:port.     

# Gather Netflow data from ONE621 on my desk
  - job_name: netflow-exporter
    static_configs:
      - targets: ['192.168.60.96:9438'] # Replace with actual hostname/IP if different
    
#  - job_name: 'dockerd-exporter'
#    dns_sd_configs:
#      - names:
#          - 'dockerd-exporter'
#        type: 'A'
#        port: 9323

  - job_name: 'ONE2560-5G localhost node-exporter'
    dns_sd_configs:
      - names:
          - 'node-exporter'
        type: 'A'
        port: 9100     

# ONE641 demo setup for monitoring of temperature and power consumption data using node exporter
  - job_name: 'one641 node-exporter'
    static_configs:
    - targets: ['192.168.60.93:9100']
      labels:
        job: 'One641'
        type: 'A'
        port: 9100    

        # This section defines recording and alerting rules.
rules:
  # Recording rule example (copies data from one metric to another with a transformation)
  - record: power_usage_watts_total
    expr: sum(node_hwmon_power_watt{chip!="unknown"}) * 60
    lan: exemplars

  # Alerting rule example (sends an alert if CPU usage exceeds 80% for 5 minutes)
  - alert: High_CPU_Usage
    expr: node_load1 > 0.8
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: High CPU Usage Detected
      description: CPU load on {{ instance }} has been above 80% for more than 5 minutes.
