# Siegfried Loeffler Marketing Demo with Ekinops OneAccess FlexCPE 
# June 2024

# configuration of the prometheus scraper
global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'promswarm'

scrape_configs:
  - job_name: 'localhost-prometheus-metrics'
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: ['localhost:9090']

# Gather SNMP data from the ONE621 on my desk
  - job_name: 'ONE621_snmp'
    static_configs:
    - targets: ['192.168.60.97']
      labels:
        job: 'One621'
    metrics_path: /snmp
    params:
      module: [if_mib, tcp_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.4.1:9116  # The SNMP exporter's real hostname:port.     

# Gather Netflow data from ONE621 on my desk
  - job_name: 'ONE621_netflow-exporter'
    static_configs:
      - targets: ['192.168.60.97:9438'] # Replace with actual hostname/IP if different

# Gather Node data from the ONE2561 that acts as Prometheus server
  - job_name: 'ONE2560-5G_localhost_nodeexporter'
    dns_sd_configs:
      - names:
          - 'node-exporter'
        type: 'A'
        port: 9100     

# ONE641 demo setup for monitoring of temperature and power consumption data using node exporter
  - job_name: 'ONE641_nodeexporter'
    static_configs:
    - targets: ['192.168.60.96:9100']
      labels:
        job: 'One641'
        type: 'A'
        port: 9100
